let str = "kartikey"
console.log(str)
console.log(str[0])
console.log(str[1])
console.log(str[2])
console.log(str[3])
console.log(str[4])
console.log(str[5])
console.log(str[6])
console.log(str[7])
console.log(str.length)
console.log(str.toUpperCase())
console.log(str.toLowerCase())
console.log(str.slice(0,4))
console.log(str.slice(4))
console.log(str.search('y'))
console.log(str.endsWith('key'))
console.log(str.startsWith('kar'))
// console.log(str.trim())
console.log(str.split(''))
console.log(str.repeat(1))
console.log(str.concat(" "))
console.log(str.indexOf('k'))
console.log(str.concat(' Ahirwar', '\n','Btech IT', '\n', 'Roll: 21036128'))